* Take output from AgSS_2010_16_Compiled.do and merge with outputs from 3-ExtractStacksData2Polygons.R


*****************  MERGE FILES *********************

* convert to panel format and label 
use "C:\Users\mmann\Dropbox\Ethiopia_Drought\Drought_Study\AgSS_Data1_2010_16_Cleaned\AgSS_2010_15_Compiled.dta", replace
reshape long PLOTS WQFERT AREAH WHEAT MAIZE BARLEY SORGHUM TEFF WHEATAREA WHEATOUTPUT WHEATOPH WHEATEXTAREA WHEATIRRGAREA WHEATSERRAREA WHEATMERR1AREA WHEATMERR2AREA WHEATMERR3AREA WHEATMERR4AREA WHEATMERR5AREA WHEATSEED1AREA WHEATSEED2AREA WHEATIMSEED WHEATNIMSEED WHEATDAMAGEAREA WHEATDAMAGE_WEATHER_AREA WHEATDAMAGE_PESTS_AREA WHEATDAMAGE_MANAGE_AREA WHEATDAMAGE_OTHER_AREA WHEATDAMAGE_DROUGHT_AREA WHEATDAMAGE_DROUGHT_DUM WHEATFERT_NATURAL_AREA WHEATFERT_CHEMICAL_AREA WHEATFERT_CHEMICAL_AMT MAIZEAREA MAIZEOUTPUT MAIZEOPH MAIZEEXTAREA MAIZEIRRGAREA MAIZESERRAREA MAIZEMERR1AREA MAIZEMERR2AREA MAIZEMERR3AREA MAIZEMERR4AREA MAIZEMERR5AREA MAIZESEED1AREA MAIZESEED2AREA MAIZEIMSEED MAIZENIMSEED MAIZEDAMAGEAREA MAIZEDAMAGE_WEATHER_AREA MAIZEDAMAGE_PESTS_AREA MAIZEDAMAGE_MANAGE_AREA MAIZEDAMAGE_OTHER_AREA MAIZEDAMAGE_DROUGHT_AREA MAIZEDAMAGE_DROUGHT_DUM MAIZEFERT_NATURAL_AREA MAIZEFERT_CHEMICAL_AREA MAIZEFERT_CHEMICAL_AMT BARLEYAREA BARLEYOUTPUT BARLEYOPH BARLEYEXTAREA BARLEYIRRGAREA BARLEYSERRAREA BARLEYMERR1AREA BARLEYMERR2AREA BARLEYMERR3AREA BARLEYMERR4AREA BARLEYMERR5AREA BARLEYSEED1AREA BARLEYSEED2AREA BARLEYIMSEED BARLEYNIMSEED BARLEYDAMAGEAREA BARLEYDAMAGE_WEATHER_AREA BARLEYDAMAGE_PESTS_AREA BARLEYDAMAGE_MANAGE_AREA BARLEYDAMAGE_OTHER_AREA BARLEYDAMAGE_DROUGHT_AREA BARLEYDAMAGE_DROUGHT_DUM BARLEYFERT_NATURAL_AREA BARLEYFERT_CHEMICAL_AREA BARLEYFERT_CHEMICAL_AMT SORGHUMAREA SORGHUMOUTPUT SORGHUMOPH SORGHUMEXTAREA SORGHUMIRRGAREA SORGHUMSERRAREA SORGHUMMERR1AREA SORGHUMMERR2AREA SORGHUMMERR3AREA SORGHUMMERR4AREA SORGHUMMERR5AREA SORGHUMSEED1AREA SORGHUMSEED2AREA SORGHUMIMSEED SORGHUMNIMSEED SORGHUMDAMAGEAREA SORGHUMDAMAGE_WEATHER_AREA SORGHUMDAMAGE_PESTS_AREA SORGHUMDAMAGE_MANAGE_AREA SORGHUMDAMAGE_OTHER_AREA SORGHUMDAMAGE_DROUGHT_AREA SORGHUMDAMAGE_DROUGHT_DUM SORGHUMFERT_NATURAL_AREA SORGHUMFERT_CHEMICAL_AREA SORGHUMFERT_CHEMICAL_AMT TEFFAREA TEFFOUTPUT TEFFOPH TEFFEXTAREA TEFFIRRGAREA TEFFSERRAREA TEFFMERR1AREA TEFFMERR2AREA TEFFMERR3AREA TEFFMERR4AREA TEFFMERR5AREA TEFFSEED1AREA TEFFSEED2AREA TEFFIMSEED TEFFNIMSEED TEFFDAMAGEAREA TEFFDAMAGE_WEATHER_AREA TEFFDAMAGE_PESTS_AREA TEFFDAMAGE_MANAGE_AREA TEFFDAMAGE_OTHER_AREA TEFFDAMAGE_DROUGHT_AREA TEFFDAMAGE_DROUGHT_DUM TEFFFERT_NATURAL_AREA TEFFFERT_CHEMICAL_AREA TEFFFERT_CHEMICAL_AMT TOTEXTAREA TOTIRRGAREA TOTSERRAREA TOTMERR1AREA TOTMERR2AREA TOTMERR3AREA TOTMERR4AREA TOTMERR5AREA TOTMERRAREA TOTDAMAGEAREA TOTDAMAGE_WEATHER_AREA TOTDAMAGE_DROUGHT_AREA HOUSEHOLD SEXHEAD, i(EACODE) j(Year)

global crops WHEAT MAIZE BARLEY SORGHUM TEFF  
 foreach crop in $crops { 
  foreach year in $years{
	label variable `crop'OUTPUT   "Output of `crop' in quintals" 
	label variable `crop'AREA "Hectares of `crop' grown"
 	label variable `crop'OPH "`crop' yield (quintals output per hectare)"
	label variable `crop'SERRAREA "`crop' not sure what this is"
	label variable `crop'MERR1AREA "`crop' hectares of Terracing"
	label variable `crop'MERR2AREA "`crop' hectares of Water Catchment"
	label variable `crop'MERR3AREA "`crop' hectares of Afforestation"
	label variable `crop'MERR4AREA "`crop' hectares of Ploughing Contour"
	label variable `crop'MERR5AREA "`crop' hectares of other mitigation efforts"
	label variable `crop'SEED1AREA "`crop' hectares of seed type 1"
	label variable `crop'SEED2AREA "`crop' hectares of seed type 1"
  }
}


save "C:\Users\mmann\Dropbox\Ethiopia_Drought\Drought_Study\AgSS_Data1_2010_16_Cleaned\AgSS_2010_15_Compiled_panel.dta", replace
*saveold "C:\Users\mmann\Dropbox\Ethiopia_Drought\Drought_Study\AgSS_Data1_2010_16_Cleaned\AgSS_2010_15_Compiled_panel.dta", version(13) replace

*use "R:\Mann_Research\IFPRI_Ethiopia_Drought_2016\IFPRI_Ethiopia_Drought_Code\Outputs4Pred\EA_NDVI_ET_panel_PCA_V3.dta"
*rename EA_cd_m EACODE
*save "R:\Mann_Research\IFPRI_Ethiopia_Drought_2016\IFPRI_Ethiopia_Drought_Code\Outputs4Pred\EA_NDVI_ET_panel_PCA_V3.dta", replace

use "C:\Users\mmann\Dropbox\Ethiopia_Drought\Drought_Study\AgSS_Data1_2010_16_Cleaned\AgSS_2010_15_Compiled_panel.dta", replace
merge 1:1 Year EACODE using "R:\Mann_Research\IFPRI_Ethiopia_Drought_2016\IFPRI_Ethiopia_Drought_Code\Outputs4Pred\EA_NDVI_ET_panel_PCA_V3.dta"
drop if _merge < 3  



*************** CALCULATE AS % OF TOTAL AREA ****************

* Generate new variables for percentage of total EA area for all variables of interest
global crops WHEAT MAIZE BARLEY SORGHUM TEFF  
global vars  EXTAREA IRRGAREA SERRAREA MERR1AREA MERR2AREA MERR3AREA MERR4AREA MERR5AREA SEED1AREA SEED2AREA IMSEED NIMSEED DAMAGEAREA DAMAGE_WEATHER_AREA DAMAGE_PESTS_AREA DAMAGE_MANAGE_AREA DAMAGE_OTHER_AREA DAMAGE_DROUGHT_AREA FERT_NATURAL_AREA FERT_CHEMICAL_AREA FERT_CHEMICAL_AMT 

foreach crop in $crops {
	foreach var in $vars {
		generate `crop'`var'_P =  `crop'`var' / `crop'AREA
	}
}


* winsorize output variables cap top 0.005% at max
global crops WHEAT MAIZE BARLEY SORGHUM TEFF  
global vars  OPH  
foreach crop in $crops {
	foreach var in $vars {
		winsor `crop'`var' , generate(`crop'`var'_W) p(0.01) highonly
		drop `crop'`var'
	}
}

* declare as panel
xtset EACODE Year, yearly 

save "R:\Mann_Research\IFPRI_Ethiopia_Drought_2016\IFPRI_Ethiopia_Drought_Code\Outputs4Pred\AgSS_2010_15_Compiled_panel_merged_clean_PCA_v3.dta", replace
save "C:\Users\mmann\Dropbox\Ethiopia_Drought\Drought_Study\AgSS_Data1_2010_16_Cleaned\AgSS_2010_15_Compiled_panel_merged_clean_PCA_v3.dta", replace
*saveold "R:\Mann_Research\IFPRI_Ethiopia_Drought_2016\IFPRI_Ethiopia_Drought_Code\AgSS_2010_15_Compiled_panel_merged_clean_v3.dta", version(13) replace
*saveold "C:\Users\mmann\Dropbox\Ethiopia_Drought\Drought_Study\AgSS_Data1_2010_16_Cleaned\AgSS_2010_15_Compiled_panel_merged_clean_v3.dta", version(13) replace

use  "R:\Mann_Research\IFPRI_Ethiopia_Drought_2016\IFPRI_Ethiopia_Drought_Code\Outputs4Pred\AgSS_2010_15_Compiled_panel_merged_clean_PCA_v3.dta", replace
* don't use log
gen LNWHEATOPH_W = ln(WHEATOPH_W) 
 
* pca v2 uses annual basis for pca to keep temporal dynamics 
  
xtreg WHEATOPH_W  i.Year i.REGIONCODE i.ZONECODE  WHEATSERRAREA  WHEATIMSEED_P WHEATFERT_NATURAL_AREA_P WHEATFERT_CHEMICAL_AMT WHEATFERT_CHEMICAL_AREA_P   WHEATEXTAREA_P WHEATIRRGAREA_P WHEATDAMAGE_WEATHER_AREA_P WHEATDAMAGE_PESTS_AREA_P  WHEATDAMAGE_MANAGE_AREA_P WHEATDAMAGE_OTHER_AREA_P WHEATDAMAGE_DROUGHT_AREA_P  A_PC1_v2 A_PC2_v2 A_PC3_v2  A_PC6_v2       G_PC1_v2 G_PC2_v2 G_PC3_v2 G_PC5_v2 G_PC10_v2    PETAET_PC4 PETAET_PC7 PETAET_PC8 PETAET_PC9    ,re
* borken  extension down by zone
xtreg WHEATOPH_W  i.Year i.REGIONCODE i.ZONECODE  WHEATSERRAREA  WHEATIMSEED_P WHEATFERT_NATURAL_AREA_P WHEATFERT_CHEMICAL_AMT WHEATFERT_CHEMICAL_AREA_P   i.REGIONCODE#c.WHEATEXTAREA_P WHEATIRRGAREA_P WHEATDAMAGE_WEATHER_AREA_P WHEATDAMAGE_PESTS_AREA_P  WHEATDAMAGE_MANAGE_AREA_P WHEATDAMAGE_OTHER_AREA_P WHEATDAMAGE_DROUGHT_AREA_P  A_PC1_v2 A_PC2_v2 A_PC3_v2  A_PC6_v2       G_PC1_v2 G_PC2_v2 G_PC3_v2 G_PC5_v2 G_PC10_v2    PETAET_PC4 PETAET_PC7 PETAET_PC8 PETAET_PC9    ,re
* borken  drought down by zone
xtreg WHEATOPH_W  i.Year i.REGIONCODE i.ZONECODE  WHEATSERRAREA  WHEATIMSEED_P WHEATFERT_NATURAL_AREA_P WHEATFERT_CHEMICAL_AMT WHEATFERT_CHEMICAL_AREA_P   i.REGIONCODE#c.WHEATEXTAREA_P WHEATIRRGAREA_P WHEATDAMAGE_WEATHER_AREA_P WHEATDAMAGE_PESTS_AREA_P  WHEATDAMAGE_MANAGE_AREA_P WHEATDAMAGE_OTHER_AREA_P i.REGIONCODE#c.WHEATDAMAGE_DROUGHT_AREA_P  A_PC1_v2 A_PC2_v2 A_PC3_v2  A_PC6_v2       G_PC1_v2 G_PC2_v2 G_PC3_v2 G_PC5_v2 G_PC10_v2    PETAET_PC4 PETAET_PC7 PETAET_PC8 PETAET_PC9    ,re
* borken  drought down by zone
xtreg WHEATOPH_W  i.Year i.REGIONCODE i.ZONECODE  WHEATSERRAREA  WHEATIMSEED_P WHEATFERT_NATURAL_AREA_P WHEATFERT_CHEMICAL_AMT WHEATFERT_CHEMICAL_AREA_P   i.REGIONCODE#c.WHEATEXTAREA_P WHEATIRRGAREA_P i.REGIONCODE#c.WHEATDAMAGE_WEATHER_AREA_P WHEATDAMAGE_PESTS_AREA_P  WHEATDAMAGE_MANAGE_AREA_P WHEATDAMAGE_OTHER_AREA_P i.REGIONCODE#c.WHEATDAMAGE_DROUGHT_AREA_P  A_PC1_v2 A_PC2_v2 A_PC3_v2  A_PC6_v2       G_PC1_v2 G_PC2_v2 G_PC3_v2 G_PC5_v2 G_PC10_v2    PETAET_PC4 PETAET_PC7 PETAET_PC8 PETAET_PC9    ,re

*NOTES:
* all  WHEATMERR5AREA_P  not helpful
* WHEATSERRAREA works WHEATSERRAREA_P doesn't 
 
 
xtreg MAIZEOPH_W  i.REGIONCODE   MAIZEEXTAREA_P MAIZEIRRGAREA_P MAIZEDAMAGEAREA_P MAIZEDAMAGE_DROUGHT_AREA_P MAIZEFERT_CHEMICAL_AMT_P A_PC1 A_PC2     G_PC1 G_PC2    PETAET_PC1 PETAET_PC2    , re

* restricted cubic splines
* http://maartenbuis.nl/presentations/bonn09.pdf


* Regresions based on variable selection algorithm (see 5a-Regressions.R)

* Interpretation phase
xtreg WHEATOPH_W  c.Year i.REGIONCODE i.ZONECODE Y_COORD X_COORD  WHEATAREA  WHEATNIMSEED WHEATFERT_CHEMICAL_AMT WHEATSEED2AREA WHEATNIMSEED_P WHEATFERT_CHEMICAL_AREA WHEATDAMAGEAREA_P WHEATFERT_CHEMICAL_AMT_P WHEATSERRAREA WHEATDAMAGEAREA WHEATMERR4AREA WHEATFERT_CHEMICAL_AREA_P WHEATDAMAGE_WEATHER_AREA_P WHEATMERR1AREA WHEATEXTAREA WHEATDAMAGE_WEATHER_AREA WHEATFERT_NATURAL_AREA WHEATIMSEED WHEATFERT_NATURAL_AREA_P WHEATSEED1AREA WHEATIMSEED_P WHEATSERRAREA_P WHEATSEED2AREA_P WHEATSEED1AREA_P WHEATMERR4AREA_P WHEATDAMAGE_PESTS_AREA WHEATEXTAREA_P WHEATMERR1AREA_P WHEATDAMAGE_DROUGHT_AREA_P WHEATMERR5AREA WHEATDAMAGE_DROUGHT_AREA WHEATMERR5AREA_P G_AUC_Qnt G_mx A_max A_Qnt A_max_Qnt A_mn G_AUC G_AUC2 G_Qnt A_AUC G_mn G_mx_Qnt T_G_Qnt G_min A_AUC_Qnt ETA_G_AUC_diff_mn PET_G_mn PET_G_sd PET_A_max PET_A_sd PET_G_AUC_trailing ETA_G_AUC_diff_90th ETA_G_mx ETA_G_Qnt PET_A_AUC ETA_G_sd PET_A_mn ETA_A_sd ETA_G_AUC2


* Prediction phase
xtreg WHEATOPH_W  WHEATNIMSEED WHEATFERT_CHEMICAL_AMT WHEATSEED2AREA WHEATNIMSEED_P WHEATFERT_CHEMICAL_AREA WHEATDAMAGEAREA_P WHEATFERT_CHEMICAL_AMT_P WHEATSERRAREA WHEATEXTAREA WHEATFERT_NATURAL_AREA WHEATIMSEED WHEATMERR4AREA_P WHEATDAMAGE_PESTS_AREA WHEATEXTAREA_P WHEATMERR1AREA_P  WHEATDAMAGE_DROUGHT_AREA_P WHEATMERR5AREA_P G_AUC_Qnt A_max_Qnt A_mn G_AUC G_mx_Qnt T_G_Qnt A_AUC_Qnt ETA_G_AUC_diff_mn PET_G_mn PET_G_sd PET_A_max PET_A_sd




